# ssh-tunnel service
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-tunnel
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 22
    name: ssh-port
    targetPort: 2222
    protocol: TCP
  selector:
    component: ssh-tunnel
  type: LoadBalancer

